root -l -b -q 'draw_nTower.C+(0.0,1.0)'
root -l -b -q 'draw_nTower.C+(0.0,3.0)'
root -l -b -q 'draw_nTower.C+(0.0,5.0)'
root -l -b -q 'draw_nTower.C+(0.0,7.0)'
root -l -b -q 'draw_nTower.C+(0.0,9.0)'

root -l -b -q 'draw_nTower.C+(1.0,0.0)'
root -l -b -q 'draw_nTower.C+(2.0,0.0)'
root -l -b -q 'draw_nTower.C+(3.0,0.0)'
root -l -b -q 'draw_nTower.C+(4.0,0.0)'
